server:
  error:
    include-message: always

server.forward-headers-strategy: NATIVE

spring:
  config:
    import: optional:file:.env[.properties]
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
