server:
  forward-headers-strategy: native
  error:
    include-message: always

spring:
  config:
    import: optional:file:.env[.properties]
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${GAMAJUN_PG_HOST}
    username: ${GAMAJUN_PG_USERNAME}
    password: ${GAMAJUN_PG_PASSWORD}
